# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - basic-test
  - extended-test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle


test_futo_4_0:
  stage: basic-test
  script: gradle run --args="research_data test_futo_4_0.txt 10000000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_4_1:
  stage: basic-test
  script: gradle run --args="research_data test_futo_4_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_4_2:
  stage: basic-test
  script: gradle run --args="research_data test_futo_4_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_5_0:
  stage: basic-test
  script: gradle run --args="research_data test_futo_5_0.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_5_1:
  stage: basic-test
  script: gradle run --args="research_data test_futo_5_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_5_2:
  stage: basic-test
  script: gradle run --args="research_data test_futo_5_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_6_0:
  stage: basic-test
  script: gradle run --args="research_data test_futo_6_0.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_6_1:
  stage: basic-test
  script: gradle run --args="research_data test_futo_6_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_6_2:
  stage: basic-test
  script: gradle run --args="research_data test_futo_6_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_7_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_7_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_7_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_7_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_0:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_0.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_4_0:
  stage: basic-test
  script: gradle run --args="research_data test_sky_4_0.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_4_1:
  stage: basic-test
  script: gradle run --args="research_data test_sky_4_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_4_2:
  stage: basic-test
  script: gradle run --args="research_data test_sky_4_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_4_3:
  stage: basic-test
  script: gradle run --args="research_data test_sky_4_3.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_4_4:
  stage: basic-test
  script: gradle run --args="research_data test_sky_4_4.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_5_0:
  stage: basic-test
  script: gradle run --args="research_data test_sky_5_0.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_5_1:
  stage: basic-test
  script: gradle run --args="research_data test_sky_5_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_5_2:
  stage: basic-test
  script: gradle run --args="research_data test_sky_5_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_5_3:
  stage: basic-test
  script: gradle run --args="research_data test_sky_5_3.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_5_4:
  stage: basic-test
  script: gradle run --args="research_data test_sky_5_4.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_0:
  stage: basic-test
  script: gradle run --args="research_data test_sky_6_0.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_1:
  stage: basic-test
  script: gradle run --args="research_data test_sky_6_1.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_2:
  stage: basic-test
  script: gradle run --args="research_data test_sky_6_2.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_4:
  stage: basic-test
  script: gradle run --args="research_data test_sky_6_4.txt 2500000"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle


test_futo_7_0_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_7_0.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_7_0_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_7_0.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_7_0_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_7_0.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_7_0_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_7_0.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_0_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_0.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_0_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_0.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_0_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_0.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_0_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_0.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_1_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_1.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_1_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_1.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_1_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_1.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_1_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_1.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_2_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_2.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_2_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_2.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_2_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_2.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_8_2_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_8_2.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_1_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_1.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_1_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_1.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_1_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_1.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_1_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_1.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_2_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_2.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_2_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_2.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_2_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_2.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_futo_9_2_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_futo_9_2.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_3_1_1:
  stage: extended-test
  script: gradle run --args="research_data test_sky_6_3.txt 10000000 1 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_3_1_2:
  stage: extended-test
  script: gradle run --args="research_data test_sky_6_3.txt 10000000 1 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_3_2_1:
  stage: extended-test
  script: gradle run --args="research_data test_sky_6_3.txt 10000000 2 1"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

test_sky_6_3_2_2:
  stage: extended-test
  script: gradle run --args="research_data test_sky_6_3.txt 10000000 2 2"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
